/* eslint-disable @typescript-eslint/no-empty-object-type */
// Generated by `supabase generate types`. Do not edit by hand.
// To regenerate, use Supabase MCP `generate_typescript_types` tool.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      fci_cartera: {
        Row: {
          activo: string
          fecha_snapshot: string
          fondo_id: number
          rank: number
          share: number
          tipo_activo: string | null
        }
        Insert: {
          activo: string
          fecha_snapshot: string
          fondo_id: number
          rank: number
          share: number
          tipo_activo?: string | null
        }
        Update: {
          activo?: string
          fecha_snapshot?: string
          fondo_id?: number
          rank?: number
          share?: number
          tipo_activo?: string | null
        }
        Relationships: []
      }
      fci_categoria: {
        Row: {
          codigo_cafci: string | null
          created_at: string
          id: number
          nombre: string
          updated_at: string
        }
        Insert: {
          codigo_cafci?: string | null
          created_at?: string
          id: number
          nombre: string
          updated_at?: string
        }
        Update: {
          codigo_cafci?: string | null
          created_at?: string
          id?: number
          nombre?: string
          updated_at?: string
        }
        Relationships: []
      }
      fci_clase: {
        Row: {
          comision_admin: number | null
          comision_ingreso: number | null
          comision_rescate: number | null
          created_at: string
          fondo_id: number
          id: number
          moneda: string | null
          monto_minimo: number | null
          nombre: string | null
          plazo_rescate: number | null
          tipo_clase_id: number | null
          tipo_clase_nombre: string | null
          updated_at: string
        }
        Insert: {
          comision_admin?: number | null
          comision_ingreso?: number | null
          comision_rescate?: number | null
          created_at?: string
          fondo_id: number
          id: number
          moneda?: string | null
          monto_minimo?: number | null
          nombre?: string | null
          plazo_rescate?: number | null
          tipo_clase_id?: number | null
          tipo_clase_nombre?: string | null
          updated_at?: string
        }
        Update: {
          comision_admin?: number | null
          comision_ingreso?: number | null
          comision_rescate?: number | null
          created_at?: string
          fondo_id?: number
          id?: number
          moneda?: string | null
          monto_minimo?: number | null
          nombre?: string | null
          plazo_rescate?: number | null
          tipo_clase_id?: number | null
          tipo_clase_nombre?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "fci_clase_fondo_id_fkey"
            columns: ["fondo_id"]
            isOneToOne: false
            referencedRelation: "fci_fondo"
            referencedColumns: ["id"]
          },
        ]
      }
      fci_estrategia_override: {
        Row: {
          codigo_cafci: number
          estrategia: string
          nota: string | null
          updated_at: string
        }
        Insert: {
          codigo_cafci: number
          estrategia: string
          nota?: string | null
          updated_at?: string
        }
        Update: {
          codigo_cafci?: number
          estrategia?: string
          nota?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      fci_fondo: {
        Row: {
          benchmark: string | null
          categoria_id: number | null
          clasificacion: string | null
          codigo_cnv: string | null
          created_at: string
          depositaria_id: number | null
          dias_liquidacion: number | null
          estado: number | null
          gestora_id: number | null
          horizonte: string | null
          id: number
          inicio: string | null
          moneda_id: number | null
          nombre: string
          objetivo: string | null
          region: string | null
          updated_at: string
        }
        Insert: {
          benchmark?: string | null
          categoria_id?: number | null
          clasificacion?: string | null
          codigo_cnv?: string | null
          created_at?: string
          depositaria_id?: number | null
          dias_liquidacion?: number | null
          estado?: number | null
          gestora_id?: number | null
          horizonte?: string | null
          id: number
          inicio?: string | null
          moneda_id?: number | null
          nombre: string
          objetivo?: string | null
          region?: string | null
          updated_at?: string
        }
        Update: {
          benchmark?: string | null
          categoria_id?: number | null
          clasificacion?: string | null
          codigo_cnv?: string | null
          created_at?: string
          depositaria_id?: number | null
          dias_liquidacion?: number | null
          estado?: number | null
          gestora_id?: number | null
          horizonte?: string | null
          id?: number
          inicio?: string | null
          moneda_id?: number | null
          nombre?: string
          objetivo?: string | null
          region?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "fci_fondo_categoria_id_fkey"
            columns: ["categoria_id"]
            isOneToOne: false
            referencedRelation: "fci_categoria"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fci_fondo_depositaria_id_fkey"
            columns: ["depositaria_id"]
            isOneToOne: false
            referencedRelation: "fci_gestora"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fci_fondo_gestora_id_fkey"
            columns: ["gestora_id"]
            isOneToOne: false
            referencedRelation: "fci_gestora"
            referencedColumns: ["id"]
          },
        ]
      }
      fci_fondo_meta: {
        Row: {
          benchmark: string | null
          clase_nombre: string
          codigo_cafci_clase: number
          duration: string | null
          fondo_id: number
          fondo_nombre: string
          horizonte: string | null
          inicio: string | null
          mm_puro: boolean | null
          region: string | null
          tipo_renta_id: number | null
          tipo_renta_nombre: string | null
          updated_at: string
        }
        Insert: {
          benchmark?: string | null
          clase_nombre: string
          codigo_cafci_clase: number
          duration?: string | null
          fondo_id: number
          fondo_nombre: string
          horizonte?: string | null
          inicio?: string | null
          mm_puro?: boolean | null
          region?: string | null
          tipo_renta_id?: number | null
          tipo_renta_nombre?: string | null
          updated_at?: string
        }
        Update: {
          benchmark?: string | null
          clase_nombre?: string
          codigo_cafci_clase?: number
          duration?: string | null
          fondo_id?: number
          fondo_nombre?: string
          horizonte?: string | null
          inicio?: string | null
          mm_puro?: boolean | null
          region?: string | null
          tipo_renta_id?: number | null
          tipo_renta_nombre?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      fci_gestora: {
        Row: {
          created_at: string
          cuit: string | null
          id: number
          miembro: boolean | null
          nombre: string
          nombre_corto: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          cuit?: string | null
          id: number
          miembro?: boolean | null
          nombre: string
          nombre_corto?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          cuit?: string | null
          id?: number
          miembro?: boolean | null
          nombre?: string
          nombre_corto?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      fci_snapshot: {
        Row: {
          calificacion: string | null
          categoria_detallada: string | null
          ccp: number | null
          codigo_cafci: number
          codigo_cnv: string | null
          com_ingreso: number | null
          com_rescate: number | null
          created_at: string
          depositaria: string | null
          fecha: string
          fee_depositaria: number | null
          fee_gestion: number | null
          fondo: string
          gestora: string | null
          hon_exito: string | null
          horizonte: string | null
          moneda: string | null
          patrimonio: number | null
          plazo_liq: number | null
          region: string | null
          var_13m: number | null
          var_dia: number | null
          var_mes: number | null
          var_ytd: number | null
          vcp: number | null
          vcp_ayer: number | null
        }
        Insert: {
          calificacion?: string | null
          categoria_detallada?: string | null
          ccp?: number | null
          codigo_cafci: number
          codigo_cnv?: string | null
          com_ingreso?: number | null
          com_rescate?: number | null
          created_at?: string
          depositaria?: string | null
          fecha: string
          fee_depositaria?: number | null
          fee_gestion?: number | null
          fondo: string
          gestora?: string | null
          hon_exito?: string | null
          horizonte?: string | null
          moneda?: string | null
          patrimonio?: number | null
          plazo_liq?: number | null
          region?: string | null
          var_13m?: number | null
          var_dia?: number | null
          var_mes?: number | null
          var_ytd?: number | null
          vcp?: number | null
          vcp_ayer?: number | null
        }
        Update: {
          calificacion?: string | null
          categoria_detallada?: string | null
          ccp?: number | null
          codigo_cafci?: number
          codigo_cnv?: string | null
          com_ingreso?: number | null
          com_rescate?: number | null
          created_at?: string
          depositaria?: string | null
          fecha?: string
          fee_depositaria?: number | null
          fee_gestion?: number | null
          fondo?: string
          gestora?: string | null
          hon_exito?: string | null
          horizonte?: string | null
          moneda?: string | null
          patrimonio?: number | null
          plazo_liq?: number | null
          region?: string | null
          var_13m?: number | null
          var_dia?: number | null
          var_mes?: number | null
          var_ytd?: number | null
          vcp?: number | null
          vcp_ayer?: number | null
        }
        Relationships: []
      }
      fci_vcp_diario: {
        Row: {
          ccp: number | null
          clase_id: number
          cuotapartistas: number | null
          fecha: string
          inserted_at: string
          patrimonio: number | null
          rend_1a: number | null
          rend_3a: number | null
          rend_5a: number | null
          rend_dia: number | null
          rend_mes: number | null
          rend_ytd: number | null
          tir_dia_tea: number | null
          tir_dia_tna: number | null
          vcp: number | null
        }
        Insert: {
          ccp?: number | null
          clase_id: number
          cuotapartistas?: number | null
          fecha: string
          inserted_at?: string
          patrimonio?: number | null
          rend_1a?: number | null
          rend_3a?: number | null
          rend_5a?: number | null
          rend_dia?: number | null
          rend_mes?: number | null
          rend_ytd?: number | null
          tir_dia_tea?: number | null
          tir_dia_tna?: number | null
          vcp?: number | null
        }
        Update: {
          ccp?: number | null
          clase_id?: number
          cuotapartistas?: number | null
          fecha?: string
          inserted_at?: string
          patrimonio?: number | null
          rend_1a?: number | null
          rend_3a?: number | null
          rend_5a?: number | null
          rend_dia?: number | null
          rend_mes?: number | null
          rend_ytd?: number | null
          tir_dia_tea?: number | null
          tir_dia_tna?: number | null
          vcp?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "fci_vcp_diario_clase_id_fkey"
            columns: ["clase_id"]
            isOneToOne: false
            referencedRelation: "fci_clase"
            referencedColumns: ["id"]
          },
        ]
      }
      instrument_blocks: {
        Row: {
          block_order: number
          block_type: string
          created_at: string
          data: Json
          id: string
          instrument_id: string
          tab_index: number
        }
        Insert: {
          block_order: number
          block_type: string
          created_at?: string
          data?: Json
          id?: string
          instrument_id: string
          tab_index: number
        }
        Update: {
          block_order?: number
          block_type?: string
          created_at?: string
          data?: Json
          id?: string
          instrument_id?: string
          tab_index?: number
        }
        Relationships: [
          {
            foreignKeyName: "instrument_blocks_instrument_id_fkey"
            columns: ["instrument_id"]
            isOneToOne: false
            referencedRelation: "instruments"
            referencedColumns: ["id"]
          },
        ]
      }
      instrument_blocks_history: {
        Row: {
          block_id: string
          block_order: number | null
          block_type: string | null
          changed_at: string
          data: Json | null
          history_id: number
          instrument_id: string
          operation: string
          tab_index: number | null
        }
        Insert: {
          block_id: string
          block_order?: number | null
          block_type?: string | null
          changed_at?: string
          data?: Json | null
          history_id?: number
          instrument_id: string
          operation: string
          tab_index?: number | null
        }
        Update: {
          block_id?: string
          block_order?: number | null
          block_type?: string | null
          changed_at?: string
          data?: Json | null
          history_id?: number
          instrument_id?: string
          operation?: string
          tab_index?: number | null
        }
        Relationships: []
      }
      instruments: {
        Row: {
          category: string
          change_dir: string | null
          change_text: string | null
          created_at: string
          id: string
          name: string
          price: string | null
          sort_order: number
          status: string
          tabs: Json
          ticker: string
          top_metrics: Json
          tv_symbol: string | null
          type: string
          updated_at: string
          updated_text: string | null
        }
        Insert: {
          category: string
          change_dir?: string | null
          change_text?: string | null
          created_at?: string
          id: string
          name: string
          price?: string | null
          sort_order?: number
          status?: string
          tabs?: Json
          ticker: string
          top_metrics?: Json
          tv_symbol?: string | null
          type: string
          updated_at?: string
          updated_text?: string | null
        }
        Update: {
          category?: string
          change_dir?: string | null
          change_text?: string | null
          created_at?: string
          id?: string
          name?: string
          price?: string | null
          sort_order?: number
          status?: string
          tabs?: Json
          ticker?: string
          top_metrics?: Json
          tv_symbol?: string | null
          type?: string
          updated_at?: string
          updated_text?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      fci_vcp_latest: {
        Row: {
          clase_id: number | null
          cuotapartistas: number | null
          fecha: string | null
          patrimonio: number | null
          rend_1a: number | null
          rend_dia: number | null
          rend_mes: number | null
          tir_dia_tea: number | null
          tir_dia_tna: number | null
          vcp: number | null
        }
        Relationships: [
          {
            foreignKeyName: "fci_vcp_diario_clase_id_fkey"
            columns: ["clase_id"]
            isOneToOne: false
            referencedRelation: "fci_clase"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
