/* eslint-disable @typescript-eslint/no-empty-object-type */
// Generated by `supabase generate types`. Do not edit by hand.
// To regenerate, use Supabase MCP `generate_typescript_types` tool.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      fci_categoria: {
        Row: {
          codigo_cafci: string | null
          created_at: string
          id: number
          nombre: string
          updated_at: string
        }
        Insert: {
          codigo_cafci?: string | null
          created_at?: string
          id: number
          nombre: string
          updated_at?: string
        }
        Update: {
          codigo_cafci?: string | null
          created_at?: string
          id?: number
          nombre?: string
          updated_at?: string
        }
        Relationships: []
      }
      fci_clase: {
        Row: {
          comision_admin: number | null
          comision_ingreso: number | null
          comision_rescate: number | null
          created_at: string
          fondo_id: number
          id: number
          moneda: string | null
          monto_minimo: number | null
          nombre: string | null
          plazo_rescate: number | null
          tipo_clase_id: number | null
          tipo_clase_nombre: string | null
          updated_at: string
        }
        Insert: {
          comision_admin?: number | null
          comision_ingreso?: number | null
          comision_rescate?: number | null
          created_at?: string
          fondo_id: number
          id: number
          moneda?: string | null
          monto_minimo?: number | null
          nombre?: string | null
          plazo_rescate?: number | null
          tipo_clase_id?: number | null
          tipo_clase_nombre?: string | null
          updated_at?: string
        }
        Update: {
          comision_admin?: number | null
          comision_ingreso?: number | null
          comision_rescate?: number | null
          created_at?: string
          fondo_id?: number
          id?: number
          moneda?: string | null
          monto_minimo?: number | null
          nombre?: string | null
          plazo_rescate?: number | null
          tipo_clase_id?: number | null
          tipo_clase_nombre?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      fci_fondo: {
        Row: {
          benchmark: string | null
          categoria_id: number | null
          clasificacion: string | null
          codigo_cnv: string | null
          created_at: string
          depositaria_id: number | null
          dias_liquidacion: number | null
          estado: number | null
          gestora_id: number | null
          horizonte: string | null
          id: number
          inicio: string | null
          moneda_id: number | null
          nombre: string
          objetivo: string | null
          region: string | null
          updated_at: string
        }
        Insert: {
          benchmark?: string | null
          categoria_id?: number | null
          clasificacion?: string | null
          codigo_cnv?: string | null
          created_at?: string
          depositaria_id?: number | null
          dias_liquidacion?: number | null
          estado?: number | null
          gestora_id?: number | null
          horizonte?: string | null
          id: number
          inicio?: string | null
          moneda_id?: number | null
          nombre: string
          objetivo?: string | null
          region?: string | null
          updated_at?: string
        }
        Update: {
          benchmark?: string | null
          categoria_id?: number | null
          clasificacion?: string | null
          codigo_cnv?: string | null
          created_at?: string
          depositaria_id?: number | null
          dias_liquidacion?: number | null
          estado?: number | null
          gestora_id?: number | null
          horizonte?: string | null
          id?: number
          inicio?: string | null
          moneda_id?: number | null
          nombre?: string
          objetivo?: string | null
          region?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      fci_gestora: {
        Row: {
          created_at: string
          cuit: string | null
          id: number
          miembro: boolean | null
          nombre: string
          nombre_corto: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          cuit?: string | null
          id: number
          miembro?: boolean | null
          nombre: string
          nombre_corto?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          cuit?: string | null
          id?: number
          miembro?: boolean | null
          nombre?: string
          nombre_corto?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      fci_vcp_diario: {
        Row: {
          ccp: number | null
          clase_id: number
          cuotapartistas: number | null
          fecha: string
          inserted_at: string
          patrimonio: number | null
          rend_1a: number | null
          rend_3a: number | null
          rend_5a: number | null
          rend_dia: number | null
          rend_mes: number | null
          rend_ytd: number | null
          tir_dia_tea: number | null
          tir_dia_tna: number | null
          vcp: number | null
        }
        Insert: {
          ccp?: number | null
          clase_id: number
          cuotapartistas?: number | null
          fecha: string
          inserted_at?: string
          patrimonio?: number | null
          rend_1a?: number | null
          rend_3a?: number | null
          rend_5a?: number | null
          rend_dia?: number | null
          rend_mes?: number | null
          rend_ytd?: number | null
          tir_dia_tea?: number | null
          tir_dia_tna?: number | null
          vcp?: number | null
        }
        Update: {
          ccp?: number | null
          clase_id?: number
          cuotapartistas?: number | null
          fecha?: string
          inserted_at?: string
          patrimonio?: number | null
          rend_1a?: number | null
          rend_3a?: number | null
          rend_5a?: number | null
          rend_dia?: number | null
          rend_mes?: number | null
          rend_ytd?: number | null
          tir_dia_tea?: number | null
          tir_dia_tna?: number | null
          vcp?: number | null
        }
        Relationships: []
      }
    }
    Views: {
      fci_vcp_latest: {
        Row: {
          clase_id: number | null
          cuotapartistas: number | null
          fecha: string | null
          patrimonio: number | null
          rend_1a: number | null
          rend_dia: number | null
          rend_mes: number | null
          tir_dia_tea: number | null
          tir_dia_tna: number | null
          vcp: number | null
        }
        Relationships: []
      }
    }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}
